env:
  SQL_URL: ${{ secrets.SQL_URL }}
  SQL_USERNAME: ${{ secrets.SQL_USERNAME }}
  SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
  JWT_KEY: ${{ secrets.JWT_KEY }}
  ACCESS_EXPIRE_TIME: ${{ secrets.ACCESS_EXPIRE_TIME }}
  REFRESH_EXPIRE_TIME: ${{ secrets.REFRESH_EXPIRE_TIME }}
  
spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test;NON_KEYWORDS=USER
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: $SQL_URL
    username: $SQL_USERNAME
    password: $SQL_PASSWORD
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true

jwt:
  key: $JWT_KEY
  accessTokenExpirationMinutes: $ACCESS_EXPIRE_TIME
  refreshTokenExpirationMinutes: $REFRESH_EXPIRE_TIME
